[provider]
cluster = "devnet"
wallet = "/Users/pindaroso/.config/solana/id.json"

[programs.localnet]
dao = "8PwBf4MonxVfJadkpSu8bLRksx4C9XfvuTDx5RzPouPj"
exchange = "7wcUmVSTQEWhz7j4ut5mMvFzZDgoyextTjY7DGtAYgdN"
factory = "3g1faa22VqQxatvFBcMTCp4fpKFsxTEnwpW6MAvCPsG5"
pyth = "3sCEFk7G6WkwREWYLaHnu1xN7cAWU7MbtZB5YEgoxUNx"

[programs.devnet]
dao = "6YLM3SRFFUy6Y2C6niZZxbA6d7hKnovCxfNTB5BXU77B"
exchange = "7DJu8o3E4bjj7gB1UQB4mD48MoUtiS8BrKW8473ddwWT"
factory = "AuCPeeS3CT1S3o2yrYjQqgJ6p3opvx1ADyHnAYRvzkt7"
pyth = "E35yEk2BLKkN4kKHKerJnAUGoAQJ2kLG39eLwBpFzmSa"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "mocha -t 1000000 tests/"
