[provider]
cluster = "devnet"
wallet = "/Users/pindaroso/.config/solana/id.json"

[programs.localnet]
dao = "3H69j4Jat4upLchz9yFoDzVdeVMVDFYSuyVC7ZsrqipY"
exchange = "2Psde5E6oLMKoU5RiLKozQMpwRq9TGP2gKCosWV8UebW"
factory = "2euwxQkkuAvVsaF3kvKuJMKb72KKDM8aHVM2pUuBC82R"
pyth = "8K39TqyCiv429v6KKmyQ82u9enwSuPH8TJdi3g5fCSwk"

[programs.devnet]
dao = "H6SCeRrELFXgFPAJZTsaAvkNr9oZTTBgF1ofMGVcZSmD"
exchange = "J2WkWo3HM45ifKKrG6Q5siV2V3zfRhKab1NhCgdV57VQ"
factory = "CDFYYHHiuhBVYPf8UL42TCn4XnpFoPhiFEzKj8GuBVgL"
pyth = "GLncE8HkQtnVP9ZcwCia4PHdveWAJ2ERoovH1E4ruLyX"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "mocha -t 1000000 tests/"
