[provider]
cluster = "localnet"
wallet = "/Users/pindaroso/.config/solana/id.json"

[programs.localnet]
dao = "8PwBf4MonxVfJadkpSu8bLRksx4C9XfvuTDx5RzPouPj"
exchange = "7wcUmVSTQEWhz7j4ut5mMvFzZDgoyextTjY7DGtAYgdN"
factory = "3g1faa22VqQxatvFBcMTCp4fpKFsxTEnwpW6MAvCPsG5"
pyth = "3sCEFk7G6WkwREWYLaHnu1xN7cAWU7MbtZB5YEgoxUNx"

[programs.devnet]
dao = "8PwBf4MonxVfJadkpSu8bLRksx4C9XfvuTDx5RzPouPj"
exchange = "7wcUmVSTQEWhz7j4ut5mMvFzZDgoyextTjY7DGtAYgdN"
factory = "3g1faa22VqQxatvFBcMTCp4fpKFsxTEnwpW6MAvCPsG5"
pyth = "3sCEFk7G6WkwREWYLaHnu1xN7cAWU7MbtZB5YEgoxUNx"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "mocha -t 1000000 tests/"
