[provider]
cluster = "devnet"
wallet = "/Users/pindaroso/.config/solana/id.json"

[programs.localnet]
dao = "4NQzmUoot2wLACXbkSZLLUAVCfjBxAx9M6sVmCSHaE38"
exchange = "5wruGah8XQEhtpALeQufRYrQSYW6FpUYw3NfWr18AHXZ"
factory = "5ZmVJ4j5iZTyBJKMKpfDqxMr1wfKVNYHheZC4tKWdeaC"
pyth = "BGVfTwcM2dTzvCTyYCoEdYdXWdYSYKGhkcEhBssJPakn"

[programs.devnet]
dao = "4NQzmUoot2wLACXbkSZLLUAVCfjBxAx9M6sVmCSHaE38"
exchange = "5wruGah8XQEhtpALeQufRYrQSYW6FpUYw3NfWr18AHXZ"
factory = "5ZmVJ4j5iZTyBJKMKpfDqxMr1wfKVNYHheZC4tKWdeaC"
pyth = "BGVfTwcM2dTzvCTyYCoEdYdXWdYSYKGhkcEhBssJPakn"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "mocha -t 1000000 tests/"
