anchor_version = "0.16.2"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
factory = "GyuPaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
exchange = "Gx9PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
pyth = "Gz9PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "mocha -t 1000000 tests/"
